import { NavBar } from '../components/NavBar';
import '../styles/globals.css';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div style={{ margin: '0 10em' }}>
          {children}
        </div>
      </body>
    </html>
  )
}
